# NumPy Yüklənməsi

In [1]:
# !pip install numpy

## NumPy import etmək

In [2]:
# import numpy
import numpy as np

# NumPy arraylərini yaratmaq



In [3]:
arr0d = np.array(53)
arr0d

array(53)

In [4]:
arr1d = np.array([1,2,3,4])
arr1d

array([1, 2, 3, 4])

In [5]:
arr2d = np.array([[1,2,3] ,
                  [4,5,6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arr3d = np.array([[[1,2,3] ,
                   [4,5,6]] ,
                  [[7,8,9] ,
                   [100,200,300]]])
arr3d

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [100, 200, 300]]])

# Built-in Functionlarla sürətli NumPy Arrayləri yaratmaq

In [7]:
np.array([1,2,3,4,5,6,7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(30,101,2)

array([ 30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,  54,
        56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,  80,
        82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [ ]:
np.linspace(30,50,6 , dtype=int) # Endpoint daxildir.

array([30, 34, 38, 42, 46, 50])

In [10]:
np.logspace(1,3 , 5) # 10**1 ilə 10**3 arasında logarifmik artış edərək 5 dənə saydan  ibarət bir array yaradır.

array([  10.        ,   31.6227766 ,  100.        ,  316.22776602,
       1000.        ])

In [11]:
np.arange(10,101,5)

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100])

In [12]:
np.linspace(0,1000,26)

array([   0.,   40.,   80.,  120.,  160.,  200.,  240.,  280.,  320.,
        360.,  400.,  440.,  480.,  520.,  560.,  600.,  640.,  680.,
        720.,  760.,  800.,  840.,  880.,  920.,  960., 1000.])

In [13]:
np.zeros(5 , dtype= 'int')

array([0, 0, 0, 0, 0])

In [14]:
np.zeros((2,3) , dtype= int)

array([[0, 0, 0],
       [0, 0, 0]])

In [15]:
np.ones(10 , dtype = int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [16]:
np.ones((3,5) , dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [17]:
np.ones((2,3,5) , dtype = int)

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [18]:
np.eye(5 , dtype = 'int') # 5x5 baş diaqonalı 1 lərdən ibarət qalan elementləri sıfır olan array yaradır

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [19]:
np.zeros((2,6) , dtype = int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [20]:
np.random.rand(3)

array([0.40044517, 0.24318265, 0.11905448])

In [21]:
np.random.rand(2,5)

array([[0.75904201, 0.02067442, 0.00924612, 0.82098825, 0.43375068],
       [0.77069521, 0.84952215, 0.4119766 , 0.49786935, 0.34361718]])

In [22]:
np.random.rand(3) * 10

array([1.50119435, 5.32009474, 4.6740628 ])

In [24]:
np.random.randint(15,50,5)

array([47, 35, 17, 25, 29])

In [25]:
np.random.randint(0,100, (3,6))

array([[68,  3, 48, 72, 67, 40],
       [73, 19, 50, 86, 13, 89],
       [70, 52, 21, 18, 79, 17]])

In [26]:
np.random.randint(0,50, (4,6))

array([[32, 31, 15, 43,  1,  9],
       [ 3, 36, 30, 37, 12,  4],
       [ 1, 18,  5, 45, 35, 37],
       [13, 36, 31, 22, 19, 38]])

# Arrayin  Shape'ini idarə etmək

In [27]:
arr0d


array(53)

In [28]:
arr1d

array([1, 2, 3, 4])

In [29]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
arr3d

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [100, 200, 300]]])

In [ ]:
# .ndim attribute

In [ ]:
arr0d.ndim


0

In [31]:
arr1d.ndim

1

In [32]:
arr2d.ndim

2

In [33]:
arr3d.ndim


3

In [34]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# .shape attribute

In [35]:
arr2d.shape

(2, 3)

In [36]:
arr3d

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [100, 200, 300]]])

In [37]:
arr3d.shape

(2, 2, 3)

# NumPy Arraylərini İndeksləmə

In [ ]:
arr1d

array([1, 2, 3, 4])

In [38]:
arr1d[3]

4

In [39]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
arr2d[0,0]

1

In [43]:
arr3d

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [100, 200, 300]]])

In [ ]:
arr3d[0][1][2]

6

In [44]:
arr3d[0,1,2]

6

In [45]:
arr3d[1][0][-1]

9

In [46]:
arr = np.arange(53,62)
arr[4]

57

# NumPy max,min funksiyaları

In [47]:
arr = np.random.randint(1,100,10)
arr

array([11, 48, 57, 32, 12, 12, 88, 19, 28, 95])

In [48]:
arr.max()

95

In [49]:
arr.argmax()

9

In [50]:
arr.min()

11

In [51]:
arr.argmin()

0

# NumPy Arraylərində Slicing(Dilimləmə)

In [52]:
arr = np.arange(50,65)
arr

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])

In [53]:
arr[5:11]

array([55, 56, 57, 58, 59, 60])

In [54]:
arr[-5:]

array([60, 61, 62, 63, 64])

In [55]:
arr[2:10:2]

array([52, 54, 56, 58])

In [56]:
arr[5:11] = 999 # Broadcasting

In [57]:
arr

array([ 50,  51,  52,  53,  54, 999, 999, 999, 999, 999, 999,  61,  62,
        63,  64])

In [58]:
arr = np.arange(-30 , 11)
arr[5:19]

array([-25, -24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14, -13,
       -12])

In [ ]:
# .dtype attribute

In [59]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
arr.dtype

dtype('int64')

In [61]:
arr2 = np.arange(100, dtype = 'float')
arr2

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97., 98., 99.])

In [62]:
arr2.dtype

dtype('float64')

In [63]:
arr3 = np.array(['a','b','c'])
arr3

array(['a', 'b', 'c'], dtype='<U1')

In [64]:
arr3.dtype

dtype('<U1')

# Bir Arrayin Dtype'ını Deyişdirmək

In [65]:
arr = np.array([1.2 , 3.5 , 5.8])
arr

array([1.2, 3.5, 5.8])

In [66]:
arr.dtype

dtype('float64')

In [67]:
arr = arr.astype('int')
arr

array([1, 3, 5])

In [68]:
arr = np.array(['5', '7', '19', '1', '22', '99', '4'])

In [69]:
arr

array(['5', '7', '19', '1', '22', '99', '4'], dtype='<U2')

In [70]:
arr = arr.astype(int)

In [71]:
arr

array([ 5,  7, 19,  1, 22, 99,  4])

In [ ]:
# 1.Done