In [1]:
import numpy as np

In [2]:
np.array([[1,2,3,4] , [5,6,7,8] , [10,20,30,40]])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 20, 30, 40]])

In [3]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [4]:
np.arange(10,100,10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [5]:
np.linspace(10,100,6)

array([ 10.,  28.,  46.,  64.,  82., 100.])

In [6]:
np.logspace(1,3, 20 )

array([  10.        ,   12.74274986,   16.23776739,   20.69138081,
         26.36650899,   33.59818286,   42.81332399,   54.55594781,
         69.51927962,   88.58667904,  112.88378917,  143.84498883,
        183.29807108,  233.57214691,  297.63514416,  379.26901907,
        483.29302386,  615.84821107,  784.75997035, 1000.        ])

In [7]:
np.zeros(4)

array([0., 0., 0., 0.])

In [8]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.ones((3,4) , dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [10]:
np.eye(3 , dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [11]:
np.identity(3 , dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [12]:
np.random.rand(3)

array([0.07730566, 0.47380136, 0.24825456])

In [13]:
np.random.rand(6)

array([0.23913661, 0.62562456, 0.93164813, 0.31339899, 0.60156376,
       0.30754973])

In [14]:
np.random.randint(10,20)

16

In [15]:
np.random.randint(10,20 , 3)

array([15, 12, 18])

In [16]:
arr2d = np.array([[1,2,3] , [4,5,6] , [10,20,30]])
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30]])

In [17]:
arr2d.ndim

2

In [18]:
arr2d.shape

(3, 3)

In [19]:
arr2d[0][-1]

3

In [20]:
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30]])

In [21]:
arr2d.max()

30

In [22]:
arr2d.argmax()

8

In [23]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arr[2:6] = 500

In [25]:
arr

array([  0,   1, 500, 500, 500, 500,   6,   7,   8,   9])

In [26]:
arr.dtype

dtype('int64')

In [27]:
arr = arr.astype('float')

In [28]:
arr

array([  0.,   1., 500., 500., 500., 500.,   6.,   7.,   8.,   9.])

# Shape

In [29]:
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30]])

In [30]:
arr2d.shape

(3, 3)

In [31]:
arr3d = np.array([[ [1,2,3] ,[4,5,6] , [10,25,35] ,[40,50,60]] , [[10,20,30] , [5,10,20] ,[11,22,33] ,[44,55,66] ]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [10, 25, 35],
        [40, 50, 60]],

       [[10, 20, 30],
        [ 5, 10, 20],
        [11, 22, 33],
        [44, 55, 66]]])

In [32]:
arr3d.ndim

3

In [33]:
arr3d.shape

(2, 4, 3)

# Bir Array'i Reshape Etme

In [34]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [10, 25, 35],
        [40, 50, 60]],

       [[10, 20, 30],
        [ 5, 10, 20],
        [11, 22, 33],
        [44, 55, 66]]])

In [35]:
arr3d.shape

(2, 4, 3)

In [36]:
arr2d = arr3d.reshape(2,12)
arr2d

array([[ 1,  2,  3,  4,  5,  6, 10, 25, 35, 40, 50, 60],
       [10, 20, 30,  5, 10, 20, 11, 22, 33, 44, 55, 66]])

In [37]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [38]:
arr2d = arr.reshape(4,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [39]:
arr3d = np.arange(30).reshape(2,3,5)
arr3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [41]:
arr3d = np.arange(120).reshape(5,2,-1)
arr3d

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
        [ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23]],

       [[ 24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47]],

       [[ 48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71]],

       [[ 72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83],
        [ 84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95]],

       [[ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107],
        [108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119]]])

In [42]:
arr = np.arange(60).reshape(2,-1,5)
arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [43]:
arr.ndim

3

In [44]:
arr.shape

(2, 6, 5)

# Arrayleri Düzleştirme(Flatten)

In [45]:
arr2d = np.arange(40).reshape(8,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [46]:
arr2d.shape

(8, 5)

In [47]:
arr = arr2d.reshape(-1)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [48]:
arr3d = np.arange(60).reshape(-1,5,4)
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]]])

In [49]:
arr3d.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [50]:
arr3d = np.random.randint(1,100,30).reshape(2,-1,3)
arr3d

array([[[79, 85, 84],
        [66, 22, 40],
        [35, 70, 94],
        [68, 23, 25],
        [59,  5, 68]],

       [[49, 31,  2],
        [22, 78, 54],
        [78, 84, 39],
        [49, 16, 95],
        [13,  2, 95]]])

In [51]:
arr3d.reshape(-1)

array([79, 85, 84, 66, 22, 40, 35, 70, 94, 68, 23, 25, 59,  5, 68, 49, 31,
        2, 22, 78, 54, 78, 84, 39, 49, 16, 95, 13,  2, 95])

# Çok ölçülü Arraylərdə Iteration(dövr)

In [52]:
arr1d = np.arange(10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
for x in arr1d:
  print(x)

0
1
2
3
4
5
6
7
8
9


In [54]:
arr2d = np.arange(20).reshape(4,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [55]:
for x in arr2d:
  print(x)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [56]:
for x in arr2d:
  for y in x:
    print(y)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [57]:
arr3d = np.arange(30).reshape(-1,3,5)
arr3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [58]:
for x in arr3d:
  for y in x:
    for z in y:
      print(z)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29


# Çox ölçülü Arraylərdə nditer() istifadəsi

In [59]:
arr3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [60]:
for x in np.nditer(arr3d):
  print(x)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29


In [61]:
arr3d = np.arange(120).reshape(2,-1,5)
arr3d

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59]],

       [[ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74],
        [ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99],
        [100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119]]])

In [62]:
for x in np.nditer(arr3d):
  print(x)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119


# Array Elementləri Arasında riyazi hesablamalar

In [63]:
arr1 = np.array([10,20,50,100])
arr2 = np.array([5,7,9,4])

In [64]:
arr1

array([ 10,  20,  50, 100])

In [65]:
arr2

array([5, 7, 9, 4])

In [66]:
arr1 + arr2

array([ 15,  27,  59, 104])

In [67]:
arr1.__add__(arr2)

array([ 15,  27,  59, 104])

In [68]:
arr1 - arr2

array([ 5, 13, 41, 96])

In [69]:
arr1.__sub__(arr2)

array([ 5, 13, 41, 96])

In [70]:
arr1 * arr2

array([ 50, 140, 450, 400])

In [71]:
arr1 ** arr2

array([          100000,       1280000000, 1953125000000000,
              100000000])

In [72]:
arr1 / arr2

array([ 2.        ,  2.85714286,  5.55555556, 25.        ])

In [73]:
arr1 // arr2

array([ 2,  2,  5, 25])

# Bir Arrayin cəminə/Ortalamasına/Variasiyasına/Standard deviation Baxmaq

In [74]:
arr = np.random.randint(0,10, 10)
arr

array([2, 0, 6, 9, 7, 7, 8, 4, 6, 6])

In [75]:
arr.sum()

55

In [76]:
arr.mean()

5.5

In [77]:
arr.var()

6.85

In [78]:
arr.std()

2.6172504656604803

In [79]:
arr

array([2, 0, 6, 9, 7, 7, 8, 4, 6, 6])

In [80]:
np.sqrt(arr)

array([1.41421356, 0.        , 2.44948974, 3.        , 2.64575131,
       2.64575131, 2.82842712, 2.        , 2.44948974, 2.44948974])

In [81]:
np.sin(arr)

array([ 0.90929743,  0.        , -0.2794155 ,  0.41211849,  0.6569866 ,
        0.6569866 ,  0.98935825, -0.7568025 , -0.2794155 , -0.2794155 ])

In [82]:
arr = np.random.randint(0,101 , 10)
print(arr.sum())
print(arr.mean())
print(arr.var())
print(arr.std())

562
56.2
1046.1599999999999
32.34439673266453


# NumPy Arraylərini Birləştirmək (Concatenate)

In [83]:
arr1 = np.array([10,20,30,70])
arr2 = np.array([100,200,600,900])

In [84]:
arr1

array([10, 20, 30, 70])

In [85]:
arr2

array([100, 200, 600, 900])

In [86]:
np.concatenate([arr1,arr2] , axis = 0 )

array([ 10,  20,  30,  70, 100, 200, 600, 900])

In [87]:
arr1 = np.array([[1,2,3] , [5,6,7]])
arr2 = np.array([[100,200,300] , [700,800,900]])

In [88]:
arr1

array([[1, 2, 3],
       [5, 6, 7]])

In [89]:
arr2

array([[100, 200, 300],
       [700, 800, 900]])

In [90]:
np.concatenate([arr1,arr2] , axis = 0)

array([[  1,   2,   3],
       [  5,   6,   7],
       [100, 200, 300],
       [700, 800, 900]])

In [91]:
np.concatenate([arr1,arr2] , axis = 1)

array([[  1,   2,   3, 100, 200, 300],
       [  5,   6,   7, 700, 800, 900]])

# Arrayləri Stackləmə

In [92]:
arr1


array([[1, 2, 3],
       [5, 6, 7]])

In [93]:
arr2

array([[100, 200, 300],
       [700, 800, 900]])

In [94]:
np.concatenate([arr1,arr2] , axis = 0)

array([[  1,   2,   3],
       [  5,   6,   7],
       [100, 200, 300],
       [700, 800, 900]])

In [95]:
np.stack([arr1,arr2] , axis = 0)

array([[[  1,   2,   3],
        [  5,   6,   7]],

       [[100, 200, 300],
        [700, 800, 900]]])

# NumPy Arraylərinde axtarış

In [97]:
arr = np.array([1,2,5,6,7,7,9,2,2,2])
arr

array([1, 2, 5, 6, 7, 7, 9, 2, 2, 2])

In [98]:
np.where(arr == 9)

(array([6]),)

In [99]:
np.where(arr == 2)

(array([1, 7, 8, 9]),)

In [100]:
np.where(arr%2 != 0 )

(array([0, 2, 4, 5, 6]),)

# NumPy'da Random library

In [101]:
# from numpy import random as rd
import numpy as np

In [102]:
np.random.rand()

0.8694615938067595

In [103]:
np.random.randn(5)

array([-0.68949736, -0.79720711, -0.31394454,  1.25698931,  1.42641357])

In [104]:
np.random.randint(low = 10 , high = 30 , size = 5)

array([13, 22, 15, 21, 12])

In [105]:
np.random.randint(10 , 30 , 5)

array([24, 15, 15, 16, 11])

In [106]:
arr

array([1, 2, 5, 6, 7, 7, 9, 2, 2, 2])

In [113]:
np.random.choice(arr)

5

In [116]:
np.random.choice([3,-1,15])

3

In [ ]:
# Done.